config/routes.rb
Demoapp::Application.routes.draw do
  resources :groups

  get "dashboard/index"

  get "user_sessions/new"

  resources :categories
  resources :products
  resources :dashboard
  resources :employees

  match 'login' => "user_sessions#new", :as => :login
  match 'logout' => "user_sessions#destroy", :as => :logout
  match 'register' => "users#new", :as => :register

  match '/home' => 'pages#home'
  match '/about' => 'pages#about'
  match '/contact' => 'pages#contact'

  resource :account, :controller => "users"
  resources :password_resets
  resources :users
  resources :user_sessions
  resources :campaigns
  resources :solutions
  resources :customers
  resources :books

  root :to => "user_sessions#new"

  resources :products do
    resources :pictures
  end

  match '*a', :to => 'errors#routing'

end

app/models/employee.rb
class Employee < ActiveRecord::Base
  has_one :picture, :as => :imageable, :dependent => :destroy

  attr_accessible :name, :picture_attributes
  accepts_nested_attributes_for :picture, :allow_destroy => true

  validates :name, :presence => { :message => "Name required" }

  validates_associated :picture
  validates :picture, :presence => true
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  helper_method :sort_column, :sort_direction
  def index
    @employees = Employee.search(params[:search]).order(sort_column + " " + sort_direction).paginate(:page => params[:page], :per_page => 4)
  end
  def new
    @employee = Employee.new
    @employee.build_picture
    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @employee }
    end
  end

  def create
    @employee = Employee.new(params[:employee])

    respond_to do |format|
      if @employee.save
        format.html { redirect_to @employee, :notice => "Employee created successfully" }
        format.json { head :no_content }
      else
        format.html {  render :action => "new" }
        format.json { render :json => @employee.errors , :location => :unprocessable_entity}
      end
    end
  end

  def show
    @employee = Employee.find(params[:id])

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @employee }
    end
  end
  def sort_column
    Employee.column_names.include?(params[:sort]) ? params[:sort] : "name"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end
end

app/helpers/employees_helper.rb
module EmployeesHelper
  def add_object_link(name, form, object, partial, where)
    html = render(:partial => partial, :locals => { :form => form}, :object => object)
    link_to_function name, %{
      var new_object_id = new Date().getTime() ;
      var html = jQuery(#{js html}.replace(/index_to_replace_with_js/g, new_object_id)).hide();
      html.appendTo(jQuery("#{where}")).slideDown('slow');
    }
  end
end

app/views/employees/_form.html.erb
<% #@employee.picture.build
%>
<%= form_for @employee do |f| %>

<div class="field">
<%= f.label :name %></br>
<%= f.text_field :name %>

<% if @employee.errors[:name].any? %>
    <%= @employee.errors[:name].first %>
<% end %>
</div>

<%= f.fields_for :picture do |builder| %>
<%= render "pictures/form", :f => builder %>
<% end %>
<div class="action">
  <%= f.submit %>
</div>

<% end %>

<!--<div id="images">-->
<%= #render :partial => "pictures/form", :locals => {:form => f}, :picture => @employee.picture.build
%>
<!--</div>-->
<%= #add_object_link("New Photo", f, @employee.picture.build, "image", "#images")
%>

app/views/employees/index.html.erb
<table class="table table-striped">
  <thead>
  <tr>
    <th><%= sortable "name" %></th>
    <th></th>
  </tr>
  <tbody>
<%= content_tag_for(:tr, @employees) do |employee| %>
  <tr>
    <td><%= employee.name %></td>
    <td><%= image_tag employee.picture.image(:small) %></td>
    <td><%= link_to 'Show', employee %></td>
    <td><%= link_to 'Edit', edit_employee_path(employee), :class => 'btn btn-mini' %></td>
    <td><%= link_to 'Destroy', employee, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-mini btn-danger'  %></td>
  </tr>
<% end %>
</tbody>
</table>
<%= paginate @employees, :remote => true %>

app/views/employees/new.html.erb
<h1>Create employee</h1>

<%= render 'form' %>

app/views/employees/show.html.erb
<%= @employee.name %>
<%= tag('br') %>


<%= image_tag @employee.picture.image(:small) %>

<%= link_to "New", new_employee_path %>