config/routes.rb
Demoapp::Application.routes.draw do
  resources :groups

  get "dashboard/index"

  get "user_sessions/new"

  resources :categories
  resources :products
  resources :dashboard
  resources :employees

  match 'login' => "user_sessions#new", :as => :login
  match 'logout' => "user_sessions#destroy", :as => :logout
  match 'register' => "users#new", :as => :register

  match '/home' => 'pages#home'
  match '/about' => 'pages#about'
  match '/contact' => 'pages#contact'

  resource :account, :controller => "users"
  resources :password_resets
  resources :users
  resources :user_sessions
  resources :campaigns
  resources :solutions
  resources :customers
  resources :books

  root :to => "user_sessions#new"

  resources :products do
    resources :pictures
  end

  match '*a', :to => 'errors#routing'

end

app/models/user.rb
class User < ActiveRecord::Base
  # attr_accessible :title, :body
  has_one :user_detail
  has_many :user_group
  has_many :group, :through => :user_group
  accepts_nested_attributes_for :user_detail, :user_group, :group, :allow_destroy => true
  attr_accessible :first_name, :last_name, :gender, :login, :email, :password, :password_confirmation, :is_active, :photo, :user_detail_attributes, :user_group_attributes
  validates :first_name, :presence => { :message => "Please enter First name" }
  validates :last_name, :presence => { :message => "Please enter Last name" }
  validates :gender, :presence => { :message => "Please select gender" }
  validates :login, :presence => { :message => "Please enter login" }
  validates :email, :presence => { :message => "Please enter Email-ID" }

  has_attached_file :photo, :styles => { :small => "150x150>" },
                    :url => "/assets/user/:id/:style/:basename.:extension",
                    :path => ":rails_root/public/assets/user/:id/:style/:basename.:extension"

  validates_attachment_presence :photo
  validates_attachment_size :photo, :less_than => 5.megabytes
  validates_attachment_content_type :photo, :content_type => ['image/jpeg', 'image/png']
  acts_as_authentic

  validates_associated :user_detail
  validates :user_detail, :presence => true
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :require_no_user, :only => [:new, :create]
  before_filter :require_user, :only => [:show, :edit, :update]

  def new
    @user = User.new
    @user.column_for_attribute(:gender).limit
    @user.build_user_detail
    #@user.build_user_group
  end

  def create
    @user = User.new(params[:user])
    @user.column_for_attribute(:gender).limit
    if @user.save
      #Mailer.welcome_email(@user).deliver
      flash[:notice] = "Account registered!"
      redirect_back_or_default account_url
    else
      render :action => :new
    end
  end

  def show
    @user = @current_user
  end

  def edit
    @user = @current_user
  end

  def update
    @user = @current_user # makes our views "cleaner" and more consistent
    if @user.update_attributes(params[:user])
      flash[:notice] = "Account updated!"
      redirect_to account_url
    else
      render :action => :edit
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<div class="control-group">
    <%= form.label :first_name %><br />
    <div class="controls">
        <%= form.text_field :first_name %><br /><br />
        <% if @user.errors[:first_name].any? %>
            <%= @user.errors[:first_name].first %><br /><br />
        <% end %>
    </div>
  </div>
  <div class="control-group">
    <%= form.label :last_name %><br />
    <div class="controls">
        <%= form.text_field :last_name %><br /><br />
        <% if @user.errors[:last_name].any? %>
            <%= @user.errors[:last_name].first %><br /><br />
        <% end %>
    </div>
  </div>
  <div class="control-group">
    <%= form.label :gender %><br />
    <div class="controls">
        <%= form.enum_select :gender %><br /><br />
        <% if @user.errors[:gender].any? %>
            <%= @user.errors[:gender].first %><br /><br />
        <% end %>
    </div>
  </div>
  <div class="control-group">
    <%= form.label :login %><br />
    <div class="controls">
        <%= form.text_field :login, form.object.new_record? ? nil : :readonly => true %><br /><br />
        <% if @user.errors[:login].any? %>
            <%= @user.errors[:login].first %><br /><br />
        <% end %>
    </div>
  </div>
  <div class="control-group">
    <%= form.label :email %><br />
    <div class="controls">
        <%= form.text_field :email %><br /><br />
        <% if @user.errors[:email].any? %>
            <%= @user.errors[:email].first %><br /><br />
        <% end %>
    </div>
  </div>
  <div class="control-group">
    <%= form.label :password, form.object.new_record? ? nil : "Change password" %><br />
    <div class="controls">
        <%= form.password_field :password %><br /><br />
        <% if @user.errors[:password].any? %>
            <%= @user.errors[:password].first %><br /><br />
        <% end %>
    </div>
  </div>
  <div class="control-group">
    <%= form.label :password_confirmation %><br />
    <div class="controls">
        <%= form.password_field :password_confirmation %><br /><br />
        <% if @user.errors[:password_confirmation].any? %>
            <%= @user.errors[:password_confirmation].first %><br /><br />
        <% end %>
    </div>
  </div>
  <div class="control-group">
    <%= form.label :is_active, "Status" %><br />
    <div class="controls">
        <%= form.select :is_active, {Active: 1, Inactive: 0} %><br /><br />
        <% if @user.errors[:is_active].any? %>
            <%= @user.errors[:is_active].first %><br /><br />
        <% end %>
    </div>
  </div>
  <div class="control-group">
    <%= form.label :photo %>
    <div class="controls">
        <% if not form.object.new_record? %>
            <% if @user.photo.exists? %>
                <%= image_tag @user.photo.url(:small), :alt => form.object.login, :title => form.object.login %>
            <% end %>
        <% end %>
        <%= form.file_field :photo %>
    </div>
  </div>


<%= render :partial => "user_details/form", :locals => {:form => form} %>

<%= render :partial => "user_groups/form", :locals => {:form => form} %>

app/views/users/edit.html.erb
Edit My Account


<%= form_for @user, :url => account_path do |f| %>
  <%= render :partial => "form", :object => f %>
  <%= f.submit "Update" %>
<% end %>

<%= link_to "My Profile", account_path %>

app/views/users/new.html.erb
Register


<%= form_for @user, :url => account_path do |f| %>

<% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<%= render :partial => "form", :object => f %>
<%= f.submit "Register" %>
<% end %>

app/views/users/show.html.erb
Login: <%=h @user.login %>

Login count: <%=h @user.login_count %>

Last request at: <%=h @user.last_request_at %>

Last login at: <%=h @user.last_login_at %>

Current login at: <%=h @user.current_login_at %>

Last login ip: <%=h @user.last_login_ip %>

Current login ip: <%=h @user.current_login_ip %>


<%= link_to 'Edit', edit_account_path %> |
<%= link_to 'Logout', :logout %>