config/routes.rb
Demoapp::Application.routes.draw do
  resources :groups

  get "dashboard/index"

  get "user_sessions/new"

  resources :categories
  resources :products
  resources :dashboard
  resources :employees

  match 'login' => "user_sessions#new", :as => :login
  match 'logout' => "user_sessions#destroy", :as => :logout
  match 'register' => "users#new", :as => :register

  match '/home' => 'pages#home'
  match '/about' => 'pages#about'
  match '/contact' => 'pages#contact'

  resource :account, :controller => "users"
  resources :password_resets
  resources :users
  resources :user_sessions
  resources :campaigns
  resources :solutions
  resources :customers
  resources :books

  root :to => "user_sessions#new"

  resources :products do
    resources :pictures
  end

  match '*a', :to => 'errors#routing'

end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :lft, :name, :parent_id, :rgt
  acts_as_nested_set

  def self.search(search)
    if search
      where('name LIKE ?', "%#{search}%")
    else
      scoped
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  helper_method :sort_column, :sort_direction

  def index
    @categories = Category.search(params[:search]).order(sort_column + " " + sort_direction).paginate(:per_page => 10, :page => params[:page])
  end

  def show
    @category = Category.find(params[:id])
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(params[:category])
    if @category.save
      flash[:notice] = "Successfully created category."
      redirect_to @category
    else
      render :action => 'new'
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update_attributes(params[:category])
      flash[:notice] = "Successfully updated category."
      redirect_to @category
    else
      render :action => 'edit'
    end
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    flash[:notice] = "Successfully destroyed category."
    format.json { redirect_to @category }
    format.js { render :nothing => true }
  end

  private

  def sort_column
    Category.column_names.include?(params[:sort]) ? params[:sort] : "lft"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_categories.html.erb
<%= hidden_field_tag :direction, params[:direction] %>
<%= hidden_field_tag :sort, params[:sort] %>
<table class="table table-striped">
  <thead>
  <tr>
    <th><%= sortable "name" %></th>
  </tr>
  </thead>
  <tbody>
  <% for category in @categories %>
    <tr>
      <td><%= "#{'-' * category.level} #{category.name}" %></td>
      <td><%= link_to "Edit", edit_category_path(category), :class => 'btn btn-mini' %></td>
      <td><%= link_to "Destroy", category, :confirm => 'Are you sure?', :method => :delete, :remote => true, :class => 'btn btn-mini btn-danger' %></td>
    </tr>
  <% end %>
</tbody>
</table>
<%= will_paginate @categories %>

app/views/categories/_form.html.erb
<%= form_for @category do |f| %>
<% if @category.errors.any? %>
    <div id="error_explanation">
      <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :parent_id %><br />
    <%= f.select :parent_id, nested_set_options(Category, @category) {|i| "#{'-' * i.level} #{i.name}" }, :include_blank => 'Select category' %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/categories/edit.html.erb
<% title "Edit Category" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @category %> |
  <%= link_to "View All", categories_path %>
</p>

app/views/categories/index.html.erb
<%= form_tag categories_path, :method => 'get', :id => "categories_search" do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search", :name => nil %>
  </p>
  <div id="categories"><%= render 'categories' %></div>
<% end %>

<p><%= link_to "New Category", new_category_path %></p>

app/views/categories/index.js.erb
$("#categories").html("<%= escape_javascript(render("categories")) %>");

app/views/categories/new.html.erb
<%= render 'form' %>

<p><%= link_to "Back to List", categories_path %></p>

app/views/categories/show.html.erb
<% title "Category" %>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>
<p>
  <strong>Parent:</strong>
  <%= @category.parent_id %>
</p>

<p>
  <%= link_to "Edit", edit_category_path(@category) %> |
  <%= link_to "Destroy", @category, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", categories_path %>
</p>